/*******************************************************************
*@author:Marcos Paulo
*@since:14/08/2012
*@task:view que traz todas as pecas que são de fornecedores BR
*@desc:
********************************************************************/
create view fornecedoresBR as 
select  feh.fornecedor_id  ,
	pu  ,
	marca_id  ,
	historico_id  ,
	data_cotacao  ,
	puc  ,
	partnumber  ,
	disponibilidade_id  ,
	oferta  ,
	qtd  ,
	moeda_preco  ,
	preco ,
	p3 ,
	p7 ,
	p12 ,
	p18 ,
	l3 ,
	l7 ,
	l12 ,
	l18 ,
	margem_lucro ,
	vc_imp_bbi_25_30_fob ,
	vc_imp_bbi_25_30_peso ,
	vc_imp_bbi_7_10 ,
	vc_imp_alemanha ,
	preco_simp ,
	aliquota_ipi ,
	moeda_custo  ,
	moeda_custo_id ,
	moeda_preco_id ,
	custo ,
	frete ,
	frete_valor ,
	frete_tempo  ,
	usuario_id  ,
	contato_id  ,
	origem  ,
	mostra_preco  ,
	ultimo  ,
	m1_custo_tot_inter_brl ,
	m2_custo_tot_inter_brl ,
	m3_custo_tot_inter_brl ,
	m4_custo_tot_inter_brl ,
	mdd_m1_vv_unit_brl ,
	mdd_m2_vv_unit_brl ,
	mdd_m3_vv_unit_brl ,
	mdd_m4_vv_unit_brl ,
	rpm_m1_vv_unit_7_brl ,
	rpm_m1_vv_unit_12_brl ,
	rpm_m1_vv_unit_18_brl ,
	rpm_m2_vv_unit_7_brl ,
	rpm_m2_vv_unit_12_brl ,
	rpm_m2_vv_unit_18_brl ,
	rpm_m3_vv_unit_7_brl ,
	rpm_m3_vv_unit_12_brl ,
	rpm_m3_vv_unit_18_brl ,
	rpm_m4_vv_unit_7_brl ,
	rpm_m4_vv_unit_12_brl ,
	rpm_m4_vv_unit_18_brl ,
	mdd_m1_lucro_tot_brl ,
	mdd_m2_lucro_tot_brl ,
	mdd_m3_lucro_tot_brl ,
	mdd_m4_lucro_tot_brl ,
	rpm_m1_lucro_tot_7_brl ,
	rpm_m2_lucro_tot_7_brl ,
	rpm_m3_lucro_tot_7_brl ,
	rpm_m4_lucro_tot_7_brl ,
	rpm_m1_lucro_tot_12_brl ,
	rpm_m2_lucro_tot_12_brl ,
	rpm_m3_lucro_tot_12_brl ,
	rpm_m4_lucro_tot_12_brl ,
	rpm_m1_lucro_tot_18_brl ,
	rpm_m2_lucro_tot_18_brl ,
	rpm_m3_lucro_tot_18_brl ,
	rpm_m4_lucro_tot_18_brl ,
	m1_custo_tot_imp_brl ,
	m2_custo_tot_imp_brl ,
	m3_custo_tot_imp_brl ,
	m4_custo_tot_imp_brl ,
	m1_disponibilidade ,
	m2_disponibilidade ,
	m3_disponibilidade ,
	m4_disponibilidade ,
	peso_kg ,
	rpm_export_vv_unit_brl ,
	mdd_export_vv_unit_brl ,
	rpm_export_lucro_unit_brl ,
	mdd_export_lucro_unit_brl ,
	matriz_id  ,
	matriz_filial ,
	nome  ,
	tipo ,
	nome_fantasia ,
	razao_social ,
	cnpj ,
	insc_est ,
	endereco ,
	bairro ,
	cep ,
	uf,
	cidade ,
	pais_sigla ,
	site ,
	email ,
	email2 ,
	tratamento ,
	contato,
	cargo,
	ddd_tel,
	tel,
	ddd_fax,
	fax,
	central  ,
	t_origem ,
	t_origem_id ,
	aliquota_icms,
	tributacao
from        fornecedor_estoque_historico as feh
left join   fornecedor                   as fnd on feh.fornecedor_id=fnd.fornecedor_id  
left join   paises                       as pai on fnd.pais_sigla=pai.sigla_pais
where       feh.preco>0
and         feh.qtd>0
and         feh.ultimo=1
and         lower(fnd.pais_sigla) = 'br';